---
name: "Monthly Release"
permissions:
  contents: write
  packages: write

# "on":
#   schedule:
#     - cron: "0 0 1 * *"

'on':
  pull_request:
    branches:
      - 'main'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v5"
      - name: Get current date
        id: pr-date
        run: echo "PR_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      - name: Create Release
        run: gh release create --draft ${{ steps.pr-date.outputs.PR_DATE }}-rc --generate-notes --title ${{ steps.pr-date.outputs.PR_DATE }}-rc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
